//
//  PokemonSpecies.swift
//  PokemonBattle
//
//  Created by Christopher Shipstone on 08/05/2026.
//

public enum PokemonSpecies : BitwiseCopyable, CaseIterable, Codable, Comparable, Hashable, Sendable {
    case bulbasaur
    case ivysaur
    case venusaur
    case charmander
    case charmeleon
    case charizard
    case squirtle
    case wartortle
    case blastoise
    case caterpie
    case metapod
    case butterfree
    case weedle
    case kakuna
    case beedrill
    case pidgey
    case pidgeotto
    case pidgeot
    case rattata
    case raticate
    case spearow
    case fearow
    case ekans
    case arbok
    case pikachu
    case raichu
    case sandshrew
    case sandslash
    case nidoranF
    case nidorina
    case nidoqueen
    case nidoranM
    case nidorino
    case nidoking
    case clefairy
    case clefable
    case vulpix
    case ninetails
    case jigglypuff
    case wigglytuff
    case zubat
    case golbat
    case oddish
    case gloom
    case vileplume
    case paras
    case parasect
    case venonat
    case venomoth
    case diglett
    case dugtrio
    case meowth
    case persian
    case psyduck
    case golduck
    case mankey
    case primeape
    case growlithe
    case arcanine
    case poliwag
    case poliwhirl
    case poliwrath
    case abra
    case kadabra
    case alakazam
    case machop
    case machoke
    case machamp
    case bellsprout
    case weepinbell
    case victreebel
    case tentacool
    case tentacruel
    case geodude
    case graveler
    case golem
    case ponyta
    case rapidash
    case slowpoke
    case slowbro
    case magnemite
    case magneton
    case farfetchd
    case doduo
    case dodrio
    case seel
    case dewgong
    case grimer
    case muk
    case shellder
    case cloyster
    case gastly
    case haunter
    case gengar
    case onix
    case drowzee
    case hypno
    case krabby
    case kingler
    case voltorb
    case electrode
    case exeggcute
    case exeggutor
    case cubone
    case marowak
    case hitmonlee
    case hitmonchan
    case lickitung
    case koffing
    case weezing
    case rhyhorn
    case rhydon
    case chansey
    case tangela
    case kangaskhan
    case horsea
    case seadra
    case goldeen
    case seaking
    case staryu
    case starmie
    case mrMime
    case scyther
    case jynx
    case electabuzz
    case magmar
    case pinsir
    case tauros
    case magikarp
    case gyarados
    case lapras
    case ditto
    case eevee
    case vaporeon
    case jolteon
    case flareon
    case porygon
    case omanyte
    case omastar
    case kabuto
    case kabutops
    case aerodactyl
    case snorlax
    case articuno
    case zapdos
    case moltres
    case dratini
    case dragonair
    case dragonite
    case mewtwo
    case mew
}
