//
//  PokemonMove+pp.swift
//  PokemonBattle
//
//  Created by Christopher Shipstone on 08/05/2026.
//

public extension PokemonMove {
    var pp: Int {
        switch self {
        case .pound:
            return 40
        case .karateChop:
            return 25
        case .doubleSlap:
            return 10
        case .cometPunch:
            return 15
        case .megaPunch:
            return 20
        case .payDay:
            return 20
        case .firePunch, .icePunch, .thunderPunch:
            return 15
        case .scratch:
            return 35
        case .viceGrip:
            return 30
        case .guillotine:
            return 5
        case .razorWind:
            return 10
        case .swordsDance:
            return 30
        case .cut:
            return 30
        case .gust:
            return 35
        case .wingAttack:
            return 35
        case .whirlwind:
            return 20
        case .fly:
            return 15
        case .bind:
            return 20
        case .slam:
            return 20
        case .vineWhip:
            return 10
        case .stomp:
            return 20
        case .doubleKick:
            return 30
        case .megaKick:
            return 5
        case .jumpKick:
            return 25
        case .rollingKick:
            return 15
        case .sandAttack:
            return 15
        case .headbutt:
            return 15
        case .hornAttack:
            return 25
        case .furyAttack:
            return 20
        case .hornDrill:
            return 5
        case .tackle:
            return 35
        case .bodySlam:
            return 15
        case .wrap:
            return 20
        case .takeDown:
            return 20
        case .thrash:
            return 20
        case .doubleEdge:
            return 15
        case .tailWhip:
            return 30
        case .poisonSting:
            return 35
        case .twineedle:
            return 20
        case .pinMissile:
            return 20
        case .leer:
            return 30
        case .bite:
            return 25
        case .growl:
            return 40
        case .roar:
            return 20
        case .sing:
            return 15
        case .supersonic:
            return 20
        case .sonicBoom:
            return 20
        case .disable:
            return 20
        case .acid:
            return 30
        case .ember:
            return 25
        case .flamethrower:
            return 15
        case .mist:
            return 30
        case .waterGun:
            return 25
        case .hydroPump:
            return 5
        case .surf:
            return 15
        case .iceBeam:
            return 10
        case .blizzard:
            return 5
        case .psybeam, .bubbleBeam, .auroraBeam:
            return 20
        case .hyperBeam:
            return 5
        case .peck:
            return 35
        case .drillPeck:
            return 20
        case .submission:
            return 25
        case .lowKick:
            return 20
        case .counter:
            return 20
        case .seismicToss:
            return 20
        case .strength:
            return 15
        case .absorb:
            return 25
        case .megaDrain:
            return 10
        case .leechSeed:
            return 10
        case .growth:
            return 40
        case .razorLeaf:
            return 25
        case .solarBeam:
            return 10
        case .poisonPowder:
            return 35
        case .stunSpore:
            return 30
        case .sleepPowder:
            return 15
        case .petalDance:
            return 20
        case .stringShot:
            return 40
        case .dragonRage:
            return 10
        case .fireSpin:
            return 15
        case .thunderShock:
            return 30
        case .thunderbolt:
            return 15
        case .thunderWave:
            return 20
        case .thunder:
            return 10
        case .rockThrow:
            return 15
        case .earthquake:
            return 10
        case .fissure:
            return 5
        case .dig:
            return 10
        case .toxic:
            return 10
        case .confusion:
            return 25
        case .psychic:
            return 10
        case .hypnosis:
            return 20
        case .meditate:
            return 40
        case .agility:
            return 30
        case .quickAttack:
            return 30
        case .rage:
            return 20
        case .teleport:
            return 20
        case .nightShade:
            return 15
        case .mimic:
            return 10
        case .screech:
            return 40
        case .doubleTeam:
            return 15
        case .recover:
            return 20
        case .harden:
            return 30
        case .minimize:
            return 20
        case .smokescreen:
            return 20
        case .confuseRay:
            return 10
        case .withdraw:
            return 40
        case .defenseCurl:
            return 40
        case .barrier:
            return 30
        case .lightScreen:
            return 30
        case .haze:
            return 30
        case .reflect:
            return 20
        case .focusEnergy:
            return 30
        case .bide:
            return 10
        case .metronome:
            return 10
        case .mirrorMove:
            return 20
        case .selfDestruct:
            return 5
        case .eggBomb:
            return 10
        case .lick:
            return 30
        case .smog:
            return 20
        case .sludge:
            return 20
        case .boneClub:
            return 20
        case .fireBlast:
            return 5
        case .waterfall:
            return 15
        case .clamp:
            return 10
        case .swift:
            return 20
        case .skullBash:
            return 15
        case .spikeCannon:
            return 15
        case .constrict:
            return 35
        case .amnesia:
            return 20
        case .kinesis:
            return 15
        case .softBoiled:
            return 10
        case .hiJumpKick:
            return 20
        case .glare:
            return 30
        case .dreamEater:
            return 15
        case .poisonGas:
            return 40
        case .barrage:
            return 20
        case .leechLife:
            return 15
        case .lovelyKiss:
            return 10
        case .skyAttack:
            return 5
        case .transform:
            return 10
        case .bubble:
            return 30
        case .dizzyPunch:
            return 10
        case .spore:
            return 15
        case .flash:
            return 20
        case .psywave:
            return 15
        case .splash:
            return 40
        case .acidArmor:
            return 40
        case .crabhammer:
            return 10
        case .explosion:
            return 5
        case .furySwipes:
            return 15
        case .bonemerang:
            return 10
        case .rest:
            return 10
        case .rockSlide:
            return 10
        case .hyperFang:
            return 15
        case .sharpen:
            return 30
        case .conversion:
            return 30
        case .triAttack:
            return 10
        case .superFang:
            return 10
        case .slash:
            return 20
        case .substitute:
            return 10
        case .struggle:
            return 10
        }
    }
}
